Minaw.wu
ch-iv/mancala pull request #10
Opened 2024-11-16 02:15 UTC by MW0808

Get leaderboard use case with basic visuals and test

2024-11-16 16:14 UTC, ch-iv requested changes
Great PR. Could you also adjust the naming of your packages to be lowercase separated by underscore (e.g `UseCase` -> `use_case`)

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Testing.java
Uncommit this file

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Config.java
> +    public static final String leaderboardFrame= "Leaderboard";
Use uppercase for constants and give it a more descriptive name like `LEADERBOARD_FRAME_NAME`

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Entities/Leaderboard.java
> +
Remove whitespace

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Entities/Leaderboard.java
Adapt the leaderboard to the format described [here](https://github.com/ch-iv/mancala/pull/11/files#diff-09ac1f7ca3996bd78c1bc6ece6c43142946fea6d66c1eb7030b492655c4571b1)

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/InterfaceAdapters/GetLeaderboardPresenter.java
> +
Remove whitespace

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Test/TestGetLeaderboard.java
All tests should go in `src/test/java/us/jonathans`. Turn it into a proper integration test or remove the file from the PR

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/InterfaceAdapters/GetLeaderboardPresenter.java
> +    public String[][] getLeaderboardData(Leaderboard leaderboard) {
Write a unit test for this function

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Entities/Leaderboard.java
> +    public Map<String, ArrayList<Integer>> sort(String type) {
Write a unit test for this

2024-11-16 16:14 UTC, ch-iv commented on src/main/java/us/jonathans/Entities/Leaderboard.java
This file should be moved to an `entities` package

2024-11-16 16:17 UTC, ch-iv commented
Also for future PRs, please give your branches more descriptive names that relate to the feature that's being implemented. An appropriate name for the branch for this PR would be `implement-leaderboard-usecase`

2024-11-22 01:09 UTC, RichardrLin approved these changes
Looks good. Great job

2024-11-22 01:10 UTC, merged