Transition info and database
ch-iv/mancala pull request #23
Opened 2024-11-27 17:12 UTC by MW0808

2024-11-27 20:26 UTC, ch-iv requested changes

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/interface_adapter/get_leaderboard/GetLeaderboardController.java
> +    public void execute() throws IOException, InterruptedException {
Do not propagate exceptions to the controller layer since they originate from the data access layer. Handle them at a lower level (with try catch).

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/interface_adapter/post_leaderboard/PostLeaderboardController.java
> +    public void execute(String username, String opponent, int score) throws IOException, InterruptedException {
Catch exceptions at a lower level.

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/use_case/get_leaderboard/GetLeaderboardInputBoundary.java
> +    void execute() throws IOException, InterruptedException;
Catch this exception at a lower level.

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/use_case/get_leaderboard/GetLeaderboardInteractor.java
> +    public void execute() throws IOException, InterruptedException {
This is probably where you want to catch this exception and tell presenter to create an unsuccessful view (probably just send empty leaderboard data to the presenter)

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/use_case/get_leaderboard/GetLeaderboardRepositoryInterface.java
> +    Leaderboard getLeaderboard() throws IOException, InterruptedException;
Remove this exception.

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/use_case/post_leaderboard/PostLeaderboardInputBoundary.java
> +    void execute(PostLeaderboardInputData postLeaderboardInputData) throws IOException, InterruptedException;
Remove this exception.

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/use_case/post_leaderboard/PostLeaderboardInteractor.java
> +    public void execute(PostLeaderboardInputData postLeaderboardInputData) throws IOException, InterruptedException {
Remove this exception.

2024-11-27 20:26 UTC, ch-iv commented on src/main/java/us/jonathans/view/JMancalaPanel.java
> +                        }
Get rid of this try catch block. If you move the error handling lower you should't need it.

2024-11-28 00:44 UTC, ch-iv approved these changes

2024-11-28 00:51 UTC, jonathanqiao1 approved these changes

2024-11-28 01:56 UTC, merged